# ！/usr/bin/env python
# -*-coding:utf-8-*-
'''
@Software:   VSCode
@File    :   db_router.PY
@Time    :   2019/04/29 12:04:33
@Author  :   Even Sand
@Version :   1.0
@Contact :   sandorn@163.com
@License :   (C)Copyright 2019-2019, NewSea
@Desc    :   None
'''

config = {
    'default': {
        'host': 'rm-8vbdh9h80t8m9smmuqo.mysql.zhangbei.rds.aliyuncs.com',
        'port': 3306,
        'user': 'sandorn',
        'passwd': '123456',
        'db': 'bxflb',
        'charset': 'utf8mb4',
    },
    'ali': {
        'host': 'rm-8vbdh9h80t8m9smmuqo.mysql.zhangbei.rds.aliyuncs.com',
        'port': 3306,
        'user': 'sandorn',
        'passwd': '123456',
        'db': 'bxflb',
        'charset': 'utf8mb4',
    },
    'aliSuper': {
        'host': 'rm-8vbdh9h80t8m9smmuqo.mysql.zhangbei.rds.aliyuncs.com',
        'port': 3306,
        'user': 'root',
        'passwd': 'Sand2808',
        'db': 'bxflb',
        'charset': 'utf8mb4',
    },
    'tx': {
        'host': 'cdb-lfp74hz4.bj.tencentcdb.com',
        'port': 10014,
        'user': 'sandorn',
        'passwd': '123456',
        'db': 'bxflb',
        'charset': 'utf8mb4',
    },
    'txSuper': {
        'host': 'cdb-lfp74hz4.bj.tencentcdb.com',
        'port': 10014,
        'user': 'root',
        'passwd': 'Sand2808',
        'db': 'bxflb',
        'charset': 'utf8mb4',
    },
    'db4free': {
        'host': 'db4free.net',
        'port': 3306,
        'user': 'sandorn',
        'passwd': 'eeM3sh4KPkp4sJ8A',
        'db': 'baoxianjihuashu',
        'charset': 'utf8mb4',
    },
}
